# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14x3GbQlNY9H8ZhN-LQ7-9lIu4UFXxdXB
"""

import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import gradio as gr
import joblib

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, f1_score, classification_report,
    confusion_matrix, ConfusionMatrixDisplay
)
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# -----------------------------
# 2) Regex + parsing
# -----------------------------
FROM_RE = re.compile(r"(?im)^from\s*:\s*(.*)$")
SUBJECT_RE = re.compile(r"(?im)^subject\s*:\s*(.*)$")

HEADER_STRIP_RE = re.compile(
    r"(?im)^(from|to|subject|cc|bcc|date|reply-to|sent|received|message-id|mime-version|content-type)\s*:\s.*$"
)

def parse_email_fields(raw_email: str):
    if not isinstance(raw_email, str):
        return "", "", ""

    from_match = FROM_RE.search(raw_email)
    subj_match = SUBJECT_RE.search(raw_email)

    from_val = from_match.group(1).strip() if from_match else ""
    subj_val = subj_match.group(1).strip() if subj_match else ""

    body = re.sub(HEADER_STRIP_RE, " ", raw_email)
    body = re.sub(r"\s+", " ", body).strip()
    if not body:
        body = raw_email.strip()

    return from_val, subj_val, body

# -----------------------------
# 3) Rules (for reasoning)
# -----------------------------
PRIORITIZE_PATTERNS = [
    r"\bmfa\b", r"\botp\b", r"\bverification\b", r"\bverify\b",
    r"\bsecurity code\b", r"\blogin code\b", r"\b2fa\b",
    r"\bpassword reset\b", r"\breset your password\b", r"\bone-time\b",
    r"\bconfirm your email\b"
]

SLOW_PATTERNS = [
    r"\bunsubscribe\b", r"\bpromo\b", r"\bpromotion\b", r"\bdiscount\b",
    r"\bsale\b", r"\bdeal\b", r"\boffer\b", r"\bmarketing\b",
    r"\bnewsletter\b", r"\bblack friday\b", r"\bcyber monday\b",
    r"\bcoupon\b"
]

# -----------------------------
# 4) Cleaning (same as training)
# -----------------------------
HEADER_RE = re.compile(
    r"(?im)^(from|to|subject|cc|bcc|date|reply-to|sent|received|message-id|mime-version|content-type)\s*:\s.*$"
)

def clean_text(s: str) -> str:
    if not isinstance(s, str):
        return ""
    t = re.sub(HEADER_RE, " ", s)
    t = re.sub(r"(https?://\S+|www\.\S+)", " url ", t)
    t = re.sub(r"\b[\w\.-]+@[\w\.-]+\.\w+\b", " email ", t)
    t = re.sub(r"\b\d+(\.\d+)?\b", " num ", t)
    t = t.lower()
    t = re.sub(r"[^a-z0-9\s]", " ", t)
    t = re.sub(r"\s+", " ", t).strip()
    return t

# -----------------------------
# 5) Load data
# -----------------------------
df = pd.read_csv("email_classification_dataset.csv").dropna(subset=["email"]).reset_index(drop=True)

df[["from", "subject", "body"]] = df["email"].apply(lambda x: pd.Series(parse_email_fields(x)))
df["priority_label"] = df.apply(lambda r: (
    "Prioritize" if any(re.search(p, f"{r['from']} {r['subject']} {r['body']}".lower()) for p in PRIORITIZE_PATTERNS)
    else "Slow" if any(re.search(p, f"{r['from']} {r['subject']} {r['body']}".lower()) for p in SLOW_PATTERNS)
    else "Default"
), axis=1)

df["model_text"] = (
    df["from"].fillna("") + " " +
    df["subject"].fillna("") + " " +
    df["body"].fillna("")
).apply(clean_text)

X = df["model_text"]
y = df["priority_label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# -----------------------------
# 6) Build and Train the Model
# -----------------------------
model = Pipeline([
    ("tfidf", TfidfVectorizer(max_features=5000, ngram_range=(1,2))),
    ("clf", LogisticRegression(max_iter=2000, class_weight="balanced", multi_class="multinomial"))
])

# FIT (TRAIN) the model before predicting
model.fit(X_train, y_train)

# -----------------------------
# 6) Metrics (computed once)
# -----------------------------
y_pred = model.predict(X_test)
ACC = accuracy_score(y_test, y_pred)
F1 = f1_score(y_test, y_pred, average="macro")
REPORT = classification_report(y_test, y_pred)
CM = confusion_matrix(y_test, y_pred, labels=model.classes_)

def cm_plot():
    fig, ax = plt.subplots(figsize=(5, 4))
    ConfusionMatrixDisplay(CM, display_labels=model.classes_).plot(
        ax=ax, cmap="Greens", colorbar=False, values_format="d"
    )
    ax.set_title("Confusion Matrix")
    plt.tight_layout()
    return fig

# -----------------------------
# 7) Inference
# -----------------------------
def predict_email_event(sender, subject, body):
    combined = f"{sender} {subject} {body}"
    cleaned_input = clean_text(combined)

    prediction = model.predict([cleaned_input])[0]
    probs = model.predict_proba([cleaned_input])[0]
    idx = int(np.where(model.classes_ == prediction)[0][0])
    confidence = probs[idx]

    text_lower = combined.lower()
    if any(re.search(p, text_lower) for p in PRIORITIZE_PATTERNS):
        reasoning = "Critical: Security/authentication trigger (MFA/OTP/verification) detected."
    elif any(re.search(p, text_lower) for p in SLOW_PATTERNS):
        reasoning = "Non-Urgent: Promotional/marketing language detected."
    else:
        reasoning = "Default: General email with no urgent or promotional triggers."

    return {"label": prediction, "reasoning": reasoning, "confidence": f"{confidence:.2%}"}

def predict_ui(sender, subject, body):
    out = predict_email_event(sender, subject, body)
    return {"label": out["label"], "reason": out["reasoning"], "confidence": out["confidence"]}

# -----------------------------
# 8) UI (green theme)
# -----------------------------
examples = [
    ["security@paypal.com", "Verification code", "123456 is your code. Expires in 10 min"],
    ["news@shop.com", "Weekend Sale!", "50% off everything. Unsubscribe here."],
]

CUSTOM_CSS = """
.gradio-container button[role="tab"]{
  color:#166534 !important;
  font-weight:700 !important;
  opacity:.65 !important;
  border-bottom: 3px solid transparent !important;
}
.gradio-container button[role="tab"][aria-selected="true"]{
  color:#16a34a !important;
  opacity:1 !important;
  border-bottom: 3px solid #22c55e !important;
}
.gradio-container button[role="tab"]:hover{
  color:#22c55e !important;
  opacity:1 !important;
}
#submit-btn{
  background:#22c55e !important;
  color:#fff !important;
  font-weight:800 !important;
  border:none !important;
}
#submit-btn:hover{ background:#16a34a !important; }
h2, h3 { color:#166534 !important; }
"""

with gr.Blocks(css=CUSTOM_CSS) as demo:
    gr.Markdown("## Email Prioritization Dashboard")

    with gr.Tabs():
        with gr.Tab("Test Email"):
            gr.Markdown("Send a test email and see label, reasoning, and confidence.")
            with gr.Row():
                with gr.Column():
                    sender  = gr.Textbox(label="Sender", placeholder="security@paypal.com")
                    subject = gr.Textbox(label="Subject", placeholder="Verification code")
                    body    = gr.Textbox(label="Body", lines=6, placeholder="123456 is your code. Expires in 10 min")
                    with gr.Row():
                        clear_btn  = gr.Button("Clear")
                        submit_btn = gr.Button("Submit", elem_id="submit-btn")
                with gr.Column():
                    pred = gr.JSON(label="Prediction")

            gr.Examples(examples=examples, inputs=[sender, subject, body])
            submit_btn.click(predict_ui, [sender, subject, body], pred)
            clear_btn.click(lambda: ("", "", "", {}), outputs=[sender, subject, body, pred])

        with gr.Tab("Metrics"):
            gr.Markdown("### Model Performance")
            with gr.Row():
                gr.Number(label="Accuracy", value=float(round(ACC, 4)))
                gr.Number(label="Macro-F1", value=float(round(F1, 4)))
            gr.Plot(value=cm_plot, label="Confusion Matrix")
            gr.Textbox(label="Classification Report", value=REPORT, lines=16)

demo.launch()